  CREATE TABLE T_CRIMINAL
   (	
   KIND VARCHAR2(30) PRIMARY KEY, 
	APART NUMBER(10), 
	PC NUMBER(10), 
	TOILET NUMBER(10), 
	PARKING NUMBER(10), 
	SCHOOL NUMBER(10), 
	SUBWAY NUMBER(10), 
	OFFICE NUMBER(10)
	)
	 