  CREATE TABLE "DB"."T_CRIMINAL" 
   (	"KIND" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"APART" NUMBER(10,0), 
	"PC" NUMBER(10,0), 
	"TOILET" NUMBER(10,0), 
	"PARKING" NUMBER(10,0), 
	"SCHOOL" NUMBER(10,0), 
	"SUBWAY" NUMBER(10,0), 
	"OFFICE" NUMBER(10,0), 
	 CONSTRAINT "T_CRIMINAL_PK" PRIMARY KEY ("KIND")
	 
	 